#!/usr/bin/env zsh
#
# The purpose of this script is to demonstrate how to preview a file or an
# image in the preview window of fzf.
#
# Dependencies:
# - https://github.com/sharkdp/bat
# - https://github.com/hpjansson/chafa
# - https://iterm2.com/utilities/imgcat
# - tree for directory preview

if [[ $# -ne 1 ]]; then
  >&2 echo "usage: $0 FILENAME[:LINENO][:IGNORED]"
  exit 1
fi

file=${1/#\~\//$HOME/}

if [[ -d $file ]]; then
    # If the file is a directory, show it as a tree
    tree -L 2 -C "$file" | head -400
    exit
fi

center=0
if [[ ! -r $file ]]; then
  if [[ $file =~ ^(.+):([0-9]+)\ *$ ]] && [[ -r ${BASH_REMATCH[1]} ]]; then
    file=${BASH_REMATCH[1]}
    center=${BASH_REMATCH[2]}
  elif [[ $file =~ ^(.+):([0-9]+):[0-9]+\ *$ ]] && [[ -r ${BASH_REMATCH[1]} ]]; then
    file=${BASH_REMATCH[1]}
    center=${BASH_REMATCH[2]}
  fi
fi

type=$(file --brief --dereference --mime -- "$file")

if [[ ! $type =~ image/ ]]; then
  if [[ $type =~ binary ]]; then
    file "$1"
    exit
  fi

  bat --style="${BAT_STYLE:-numbers}" --color=always --pager=never --highlight-line="${center:-0}" -- "$file"
  exit
fi

dim=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}
if [[ $dim = x ]]; then
  dim=$(stty size < /dev/tty | awk '{print $2 "x" $1}')
elif ! [[ $KITTY_WINDOW_ID ]] && (( FZF_PREVIEW_TOP + FZF_PREVIEW_LINES == $(stty size < /dev/tty | awk '{print $1}') )); then
  # Avoid scrolling issue when the Sixel image touches the bottom of the screen
  # * https://github.com/junegunn/fzf/issues/2544
  dim=${FZF_PREVIEW_COLUMNS}x$((FZF_PREVIEW_LINES - 1))
fi

# 1. Use icat (from Kitty) if kitten is installed
if [[ $KITTY_WINDOW_ID ]] || [[ $GHOSTTY_RESOURCES_DIR ]] && command -v kitten > /dev/null; then
  # 1. 'memory' is the fastest option but if you want the image to be scrollable,
  #    you have to use 'stream'.
  #
  # 2. The last line of the output is the ANSI reset code without newline.
  #    This confuses fzf and makes it render scroll offset indicator.
  #    So we remove the last line and append the reset code to its previous line.
  kitten icat --clear --transfer-mode=memory --unicode-placeholder --stdin=no --place="$dim@0x0" "$file" | sed '$d' | sed $'$s/$/\e[m/'

# 2. Use chafa with Sixel output
elif command -v chafa > /dev/null; then
  chafa -s "$dim" "$file"
  # Add a new line character so that fzf can display multiple images in the preview window
  echo
# 4. If chafa is not found but imgcat is available, use it on iTerm2
# elif command -v imgcat > /dev/null; then
#   # NOTE: We should use https://iterm2.com/utilities/it2check to check if the
#   # user is running iTerm2. But for the sake of simplicity, we just assume
#   # that's the case here. -W "${dim%%x*}" -H "${dim##*x}"
#   imgcat -W "${dim%%x*}" -H "${dim##*x}" "$file"
#   echo
#   exit
# 3. Use catimg if it is available
elif command -v catimg > /dev/null; then
  catimg -w "${dim%%x*}" "$file"

# 4. Cannot find any suitable method to preview the image
else
  # If not a file, treat as a command: show help/man for the deepest subcommand possible
  cmdline="$input"
  args=(${(z)cmdline})

  for ((i=${#args[@]}; i>0; i--)); do
    try_cmd=(${args[@]:0:$i})
    if "${try_cmd[@]}" --help &>/dev/null; then
      "${try_cmd[@]}" --help | head -40
      exit
    fi
    if "${try_cmd[@]}" -h &>/dev/null; then
      "${try_cmd[@]}" -h | head -40
      exit
    fi
    manpage="${(j/-/)try_cmd}"
    if man "$manpage" &>/dev/null; then
      man "$manpage" | col -bx | head -40
      exit
    fi
    # Try man for just the root command if above fails
    if [[ $i -eq 1 ]] && man "${try_cmd[1]}" &>/dev/null; then
      man "${try_cmd[1]}" | col -bx | head -40
      exit
    fi
    # Try help for just the root command
    if [[ $i -eq 1 ]] && "${try_cmd[1]}" --help &>/dev/null; then
      "${try_cmd[1]}" --help | head -40
      exit
    fi
    if [[ $i -eq 1 ]] && "${try_cmd[1]}" -h &>/dev/null; then
      "${try_cmd[1]}" -h | head -40
      exit
    fi
  done
  file "$file"
fi
